"""DateTime experimentations no2

Revision ID: 07f09e732e9d
Revises: f532e6d4d5d7
Create Date: 2024-07-26 19:10:04.409539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f09e732e9d'
down_revision: Union[str, None] = 'f532e6d4d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
