"""Admin rights implementation

Revision ID: 8a0676a96b1a
Revises: 45345cddfbdd
Create Date: 2024-07-30 17:10:19.004799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0676a96b1a'
down_revision: Union[str, None] = '45345cddfbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_Admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_Admin')
    # ### end Alembic commands ###
