"""Version5

Revision ID: c94221f27772
Revises: 8a0676a96b1a
Create Date: 2024-08-08 13:57:53.373009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94221f27772'
down_revision: Union[str, None] = '8a0676a96b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('userImgUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'userImgUrl')
    # ### end Alembic commands ###
